# Generated by Django 2.1.3 on 2018-11-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineonos',
            new_name='linenos',
        ),
    ]
